export const icons: { name: string; path: string }[] = [
  { name: 'vuejs', path: 'assets/icons/vuejs.svg' },
  { name: 'react', path: 'assets/icons/react.svg' },
  { name: 'brain', path: 'assets/icons/brain-solid.svg' },
  { name: 'keras', path: 'assets/icons/keras.svg' },
  { name: 'github', path: 'assets/icons/github.svg' },
  { name: 'gitlab', path: 'assets/icons/gitlab.svg' },
  { name: 'python', path: 'assets/icons/python.svg' },
  { name: 'flask', path: 'assets/icons/flask.svg' },
  { name: 'mqtt', path: 'assets/icons/mqtt.svg' },
  { name: 'angular', path: 'assets/icons/angular.svg' },
  { name: 'aws-cloudfront', path: 'assets/icons/aws-cloudfront.svg' },
  { name: 'aws-s3', path: 'assets/icons/aws-s3.svg' },
  { name: 'aws-route53', path: 'assets/icons/aws-route53.svg' },
  { name: 'devices', path: 'assets/icons/devices.svg' },
  { name: 'golang-gopher', path: 'assets/icons/golang-gopher.svg' },
  { name: 'nestjs', path: 'assets/icons/nestjs.svg' },
  { name: 'digitalocean', path: 'assets/icons/digitalocean.svg' },
  { name: 'typescript', path: 'assets/icons/typescript.svg' },
  { name: 'npm', path: 'assets/icons/npm.svg' },
  { name: 'read-book', path: 'assets/icons/read-book.svg' }
];
